
FL_lo = shaperead ( 'usastatelo', ...
    'UseGeoCoords', true,...
    'Selector', { @ ( name ) strcmpi( name, 'Florida' ), 'Name' } );
AL_lo = shaperead ( 'usastatelo', ...
    'UseGeoCoords', true,...
    'Selector', { @ ( name ) strcmpi( name, 'Alabama' ), 'Name' } );
LA_lo = shaperead ( 'usastatelo', ...
    'UseGeoCoords', true,...
    'Selector', { @ ( name ) strcmpi( name, 'Louisiana' ), 'Name' } );
GA_lo = shaperead ( 'usastatelo', ...
    'UseGeoCoords', true,...
    'Selector', { @ ( name ) strcmpi( name, 'Georgia' ), 'Name' } );
MS_lo = shaperead ( 'usastatelo', ...
    'UseGeoCoords', true,...
    'Selector', { @ ( name ) strcmpi( name, 'Mississippi' ), 'Name' } );
SC_lo = shaperead ( 'usastatelo', ...
    'UseGeoCoords', true,...
    'Selector', { @ ( name ) strcmpi( name, 'South Carolina' ), 'Name' } );

state_color = [1 1 1]*190/255;

figure;
latlim = [24 32];
lonlim = [-93 -79.5];
ax = usamap(latlim,lonlim);
geoshow ( FL_lo, 'FaceColor',state_color);
geoshow ( AL_lo, 'FaceColor',state_color);
geoshow ( LA_lo, 'FaceColor',state_color);
geoshow ( GA_lo, 'FaceColor',state_color);
geoshow ( MS_lo, 'FaceColor',state_color);
geoshow ( SC_lo, 'FaceColor',state_color);
gridm('fontsize',16);
plotm(30.0599,-85.6811,'r.','markersize',20);  % location of FORA array